Cargo.lock, Cargo.toml, examples/all_basic_shapes.rs, examples/paths.rs, src/lib.rs
Updates to latest master which should become 0.3 soon.
EDIT: 5 minutes later bevy 0.3 got released...
=> Update to bevy 0.3

src/lib.rs, src/plugin.rs, src/shapes.rs
=> Refactor to make modules self-contained

examples/polygon.rs, src/shapes.rs
Added regular polygons:
- polygons are drawn with their base parallel to the x-axis (visually pleasing)
- size of the polygon can be specified choosing from side length, radius or apothem.
=> Add regular polygons

examples/multishape.rs, src/lib.rs, src/plugin.rs, src/shapes.rs
This PR adds the `Multishape` struct, that can be used to draw multiple shapes. An example has been added to show usage.
=> Add multishape

src/shapes.rs
- Added `CustomCenter` enum variant for `RectangleOrigin`
- Added `Line` `ShapeSprite`
=> Improve shapes

examples/balloon.rs, examples/multishape.rs, examples/polygon.rs, examples/readme_example.rs, examples/transparency.rs, src/plugin.rs
Hi, 
I noticed that the `bevy_master` branch curently does not compile.
Here is a PR to make it compile again.
P.S: Thanks for this cool library ;-)
=> Update the bevy_master branch

src/plugin.rs
A small fix to make the `bevy_master` branch work with the latest changes in Bevy master.
=> Bevy master-branch fix

Cargo.toml, examples/demo/demo_camera_plugin.rs, examples/demo/demo_inspector_plugin.rs, examples/demo/main.rs, examples/readme_example.rs, examples/svg_path_shape_example.rs, rustfmt.toml, src/lib.rs, src/plugin.rs, src/shapes.rs
`master` branch now follows Bevy's `main` branch.
=> Sync to bevy main branch

examples/readme_example.rs, examples/svg_path_shape_example.rs, src/entity.rs, src/geometry.rs, src/lib.rs, src/plugin.rs, src/render/mod.rs, src/render/shape.frag, src/render/shape.vert
Created a custom render graph node containing a `ShapeMaterial` color.
Removed any connection with Bevy `Sprite`s.
=> Render graph

examples/readme_example.rs, examples/svg_path_shape_example.rs, src/entity.rs, src/geometry.rs, src/lib.rs, src/plugin.rs, src/render/mod.rs, src/render/shape.frag, src/render/shape.vert, src/utils.rs
Added `DrawMode::Outlined` to draw filled shapes with an outline.
=> Outlined shapes

src/entity.rs, src/geometry.rs, src/plugin.rs
- Tidying up imports
- Made use of `StageLabel` trait
- Fixed doclinks
=> General improvements

src/render/shape.vert
Small correction to vertex shader after merging #86. I forgot to make the input vertex position a vec2.
=> Fix vertex shader

examples/readme_example.rs, examples/svg_path_shape_example.rs, src/geometry.rs, src/render/shape.vert
- New bevy commands naming scheme: fix breaking changes
- Vertex shader: change `Camera` uniform name to `CameraViewProj`
=> Bevy main update

Cargo.toml, README.md
Addresses https://github.com/Nilirad/bevy_prototype_lyon/issues/89
Also updated the README example
=> Fix build for Bevy 0.5

examples/readme_example.rs, examples/svg_path_shape_example.rs, src/plugin.rs
- Changed `App::build` with `App::new` and other minor changes due to `AppBuilder` removal.
- Removed `.system()` occurrences.
=> Update to bevy main

examples/change_shape_example.rs, src/plugin.rs
Fixes #11 
Fixes #104 
If this isn't going in a direction you're into, please feel free to close this.
=> Handle shape changes

examples/readme.rs, examples/svg.rs, examples/ui.rs
Reducing MSAA samples to 4 since using 8 causes a WGPU error, at least on my machine.
=> Reduce MSAA samples to 4 in examples

Cargo.toml, README.md
Bumped version and changed readme.
=> Prepare for version 0.4

README.md
Because I always have to forget something.
=> Update changelog and Bevy support table

src/geometry.rs, src/path.rs
=> Use assert_is_system

src/render/mod.rs
Fixing code due to a breaking change caused by:
- bevyengine/bevy#4189
=> Update `FloatOrd` import

examples/svg.rs, src/render/mod.rs, src/render/shape.wgsl
This fixes recent breakage and makes all examples work again.
=> Update for new bevy breaking changes

examples/dynamic_shape.rs, examples/path.rs, examples/readme.rs, examples/svg.rs
Some ergonomics ECS API adaptations since now `Component` implements `Bundle`.
=> Ecs adaptations

src/render/mod.rs
Fixes #177 
Support HDR rendering
=> specialize texture format on HDR

examples/dynamic_shape.rs, examples/path.rs, examples/readme.rs, examples/svg.rs, src/render/mod.rs
Adaptation to the changes caused by bevyengine/bevy#7292
=> Comply to Bevy API breaking change

examples/dynamic_shape.rs, examples/path.rs, examples/readme.rs, examples/svg.rs, src/draw.rs, src/entity.rs, src/geometry.rs, src/lib.rs, src/plugin.rs
Opening for discussion. IMO, this change feels pretty good in action.
Fixes #162
=> Make FillMode and StrokeMode components

CONTRIBUTING.md
Just fixes a typo in `CONTRIBUTING.md`.
=> Fix a small typo

src/plugin.rs
- Fixes an API breakage due to bevyengine/bevy#9247
=> Use `configure_sets` API

README.md
=> Update bevy tracking link

examples/dynamic_shape.rs, examples/path.rs, examples/readme.rs, examples/rounded_polygon.rs, src/draw.rs, src/geometry.rs, src/plugin.rs, src/vertex.rs
- ~~The example `dynamic_shape` does not work, maybe due to some sort of delay that doesn't catch up before the shape gets redrawn.~~ Fixed upstream.
=> Migrate to `bevy_color`
