src/lib.rs
The current version of this ~~crate~~ repo(?) fails to build with the latest github version of bevy as `Sprite` doesn't have `resize_mode` defined. 
Adding defaults fixes the issue on the master branch of bevy. I haven't tested this with bevy `0.1.3`.
=> Add defaults to sprite in create_sprite

Cargo.lock, Cargo.toml, examples/all_basic_shapes.rs, examples/paths.rs, src/basic_shapes.rs, src/lib.rs, src/path.rs
`Translation`  was removed in 0.2.0 and replaced by `Transform`. This PR replaces `Translation`, but retains the use of `Vec3`s as long as possible to keep the API mostly compatible.
P.S. I just realised I haven't touched the README or examples which should probably be updated!
=> Update for new Transform in bevy 0.2.0

Cargo.lock, Cargo.toml, src/lib.rs
A small fix of an errors coming from changes in upstream. Also, point master to the HEAD of bevy's master branch.
* Closes #8 
* The examples run properly.
=> Fix to master bevy

README.md
Two issues:
1) missing comma on penultimate argument,
2) `add_default_plugins()` instead of `.add_plugins(DefaultPlugins)` (a backwards-incompatible [bevy 0.3 change](https://bevyengine.org/news/bevy-0-3/#plugin-groups).)
After fixing those two issues, the example works on my machine (red circle on grey background).
=> Fix readme example.

src/lib.rs, src/shapes.rs
`Polygon` uses a `Vec` inside, and thus isn't `Copy`-able and can't be made `Copy`. This means the `draw` method wouldn't work as this required `Copy`. `Polygon` can be made to support Clone. So loosen restrictions to work with `Clone`.
=> Make Polygon draw work

src/plugin.rs
This change removes the ShapeDescriptor from entities and attaches the new SpriteBundle to them rather than despawning and respawning the entire entity. This allows user code to attach components to the entity, store it's Entity for future use or place it in a hierarchy.
There is some cost to changing the entity's archetype but I suspect it's not meaningfully different than the cost of despawning and creating a new entity, possibly less. I believe Cart is currently working on changes to the ECS that make that cost even smaller so I don't think it's a concern unless there is evidence of a problem.
=> Preserve entity when instantiating ShapeDescriptors

Cargo.toml, src/conversions.rs, src/entity.rs, src/lib.rs, src/path.rs, src/plugin.rs, src/shapes.rs
- `Tessellator` struct. Redundant.
- `ShapeDescriptor` and `SpriteBundle` have been replaced by `ShapeBundle`.
=> General refactoring

Cargo.toml, examples/svg_path_shape_example.rs, src/shapes.rs
I discussed this already with Nilirad, basically added a shape that takes a String description of an SVG path and outputs a shape bundle like all the other shapes.
original problems were:
1) The SVG turned out upside down at the start
* Fixed: after discussing with Nilirad I multiplied all y components of the path string and its curves by -1 to reflect that Bevy's y is the opposite of the browser's and now this is no longer an issue (at the very least relative_move_to, realtive_line_to, relative_cubic_to, and maybe relative_vertical(?) work, the others I haven't checked)
2) The SVG can be off its transform component by a lot if the M/m component of the path string is not 0.0, 0.0. 
for now, this is written in the example, and I added to it the fact that if you have two or more paths in …
=> Added SvgPathShape to shapes and an example for it with a bit of documentation

src/shapes.rs
=> Order struct fields in shorthand construction

Cargo.toml, examples/readme_example.rs, examples/svg_path_shape_example.rs, src/entity.rs, src/lib.rs, src/plugin.rs, src/render/mod.rs, src/render/shape.frag, src/render/shape.vert, src/shapes.rs
I added a custom rendering pipeline for `ShapeBundle` in order to fix a backface culling incompatibility between lyon and the new Bevy sprite pipeline.
=> Fix bevy ECS V2 breaking changes 

src/lib.rs, src/plugin.rs, src/shapes.rs
There were many `clippy::clippy::lint` forms instead of the `clippy::lint` correct form. In previous versions this was accepted, but not anymore.
This pr fixes the attributes with the correct namespaces.
=> Fix clippy namespace recursions

src/render/mod.rs
Updated the pipeline descriptor to reflect the API changes of bevy_render after updating to wgpu 0.8.
=> Adapt to Bevy breaking changes for wgpu 0.8 update

src/entity.rs, src/plugin.rs
- Fixes #108 
A shape initially invisible, becomes visible after 3 seconds.
```rust
use bevy::prelude::*;
use bevy_prototype_lyon::prelude::*;
struct Hook;
fn main() {
App::new()
.insert_resource(Msaa { samples: 8 })
.add_plugins(DefaultPlugins)
.add_plugin(ShapePlugin)
.add_startup_system(setup_system)
.add_system(make_shape_visible_system)
.run();
}
fn setup_system(mut commands: Commands) {
let shape = shapes::RegularPolygon {
sides: 6,
feature: shapes::RegularPolygonFeature::Radius(200.0),
..shapes::RegularPolygon::default()
};
commands.spawn_bundle(OrthographicCameraBundle::new_2d());
let mut shape_bundle = GeometryBuilder::build_as(
&shape,
ShapeColors::outlined(Color::TEAL, Color::BLACK),
DrawMode::Outlined {
fill_options: FillOptions::default(),
outline_options: …
```
=> Make possible to spawn invisible shapes

src/plugin.rs
Fixes #107
I saw this mentioned in discord by another user and figured I'd actually look into it.
Should work just as well for bevy 0.5 as main, but I am not sure what your process is for doing minor releases.
This seems like the correct thing to do based on how colors seem to get treated for bevy's sprite pipeline, but I'm not very familiar with bevy's rendering code. 
So if this seems wrong or if merging complicates releasing a fix for 0.3, feel free to close and reimplement (or not)
=> Fix colors not matching bevy sprites

examples/change_shape_example.rs, examples/svg_path_shape_example.rs, examples/ui.rs, src/draw.rs, src/entity.rs, src/geometry.rs, src/lib.rs, src/path.rs, src/plugin.rs
The `main` branch of Bevy now requires `Component`s to be explicitly defined. I added `#[derive(Component)]` where necessary. I also wrapped `lyon_tessellation::path::Path` into a `Path` newtype in order to derive the `Component` trait on it.
=> Use #[derive(Component)]

Cargo.toml
This PR pins the last commit of Bevy that still has the old renderer. This will be reverted when I'll push the render pipeline compatible with the new renderer.
If you are depending on bleeding edge `bevy_prototype_lyon`, you will have to pin your bevy dependency as well, like:
```toml
bevy = {git = "https://github.com/bevyengine/bevy", rev = "de8edd3"}
```
Keep in mind that this will hold you back to the old renderer, but it is necessary for now if you wank to keep using `bevy_prototype_lyon`.
**I'll do my best to deliver the new pipeline as soon as possible.** I'm quite busy these days, so it could take from some days to some weeks to sort out this issue.
=> Temporarily keep the old Bevy renderer

src/geometry.rs, src/path.rs
Complies to the recently added [`return_self_not_must_use`](https://rust-lang.github.io/rust-clippy/master/index.html#return_self_not_must_use) clippy lint
=> Apply clippy lints

examples/dynamic_shape.rs, src/entity.rs, src/path.rs, src/render/mod.rs
- Removed usage of prelude on dependencies
- Adjusted the starting number of sides in the `dynamic_shape` example. It now starts as a triangle, and gradually becomes an octagon, back and forth.
=> Random improvements

examples/path.rs, src/entity.rs, src/geometry.rs
Fixes:
- #138 
---
- Moved `Geometry` implementation from Lyon's `Path` to the wrapper `Path` defined locally (that implements `Component`).
- Added path example to avoid breaking the API unexpectedly.
=> Implement `Geometry` for `Path`

src/plugin.rs, src/render/mod.rs, src/render/shape.wgsl, src/vertex.rs
- Rename `Mesh::set_attribute` to `Mesh::insert_attribute`
- Use new `VertexBufferLayout::from_vertex_formats`
- Change vertex color attribute to a `u32`, obtained from new Color::as_linear_rgba_u32
=> Update vertex attributes to bevy main

Cargo.toml, README.md
This version will support Bevy `0.7`.
Closes #153.
=> `bevy_prototype_lyon 0.5`

src/plugin.rs
This allows much more flexibility when building shapes. Currently, any shape building code must occur in or before `Update`, or else there will be visual flickering due to the frame delay. Moving the stage after `PostUpdate` gives the programmer more freedom, and allows shapes to be based on up-to-date `GlobalTransform`s.
=> Remove dedicated `SystemStage`

examples/svg.rs
Originally just wanted to fix the issue with cargo fmt which was maddening, but noticed some other opportunities to clean things up.
- Define svg paths in multiline const literals so that cargo fmt will work. See https://github.com/rust-lang/rustfmt/issues/3863
- Fix shack not showing up at all due to missing SpatialBundle members
- Use Bevy's SpatialBundle
I ended up removing `BuildingBundle` just because I thought the code ended up looking cleaner than
- adding `SpatialBundle` to `BuildingBundle` as a nested bundle. (need to then write a `Default` impl)
- adding each component of `SpatialBundle` manually to `BuildingBundle`. (doesn't seem right to do this in an example)
- removing the spatial stuff from BuildingBundle so that only `Name` remains
But I'm happy to do any of those things …
=> Clean up SVG example

Cargo.toml
- After bevyengine/bevy#5447, assets are behind the `bevy_asset` feature flag.
- Add the `bevy_asset` feature to the `bevy` dependency and dev-dependency.
=> Add `bevy_asset` feature

README.md
The readme got updated for the release, but the main branch is still showing an outdated example, changelog, and support table.
Just copied the file over from the release branch.
=> Update README for 0.6.0

src/plugin.rs, src/render/mod.rs
- After bevyengine/bevy#5577 got merged, the `Resource` trait must be explicitely implemented.
I derived `Resource` for all the previous resources, and I created `#[derive(Resource)]` newtypes for external types that were used as resources.
=> Explicitely derive resources

src/shapes.rs
Fixes https://github.com/Nilirad/bevy_prototype_lyon/issues/179
This fixes an issue with the rectangle shape building that was introduced when the call to Rect::new was changed to a Box2d::new (the former takes extrema points and the latter takes an origin and size).
@Nilirad  Do you think it's possible to bump the minor version for it?
=> Fix rectangle shape origin and size

src/geometry.rs
In Bevy, `Commands::spawn_bundle` has been removed in favor of `Commands::spawn`. I changed two tests to accomodate for the API change.
=> Fix test to pass CI

src/plugin.rs, src/render/mod.rs
This is a first attempt to porting the library to Bevy's stageless schedule. It compiles, but at the moment the examples panic for a dependency cycle in the schedule.
=> Port to stageless schedule

src/entity.rs, src/geometry.rs
This flattens `ShapeBundle` to remove the nested `MaterialMesh2dBundle`.
This fixes a UX issue introduced by #196 where if a user wants to spawn a `ShapeBundle` with an overridden component, they would have to do something silly like
```rust
let mut shape_bundle = GeometryBuilder::build_as(
&shape,
DrawMode::Outlined {
fill_mode: FillMode::color(Color::CYAN),
outline_mode: StrokeMode::new(Color::BLACK, 10.0),
},
Transform::default(),
);
shape_bundle.mesh2d_bundle.visibility = Visibility::Hidden;
commands.spawn((
shape_bundle,
ExampleShape,
));
// Or (not bevy best-practice for performance)
commands
.spawn((
GeometryBuilder::build_as(
&shape,
DrawMode::Outlined {
fill_mode: FillMode::color(Color::CYAN),
outline_mode: StrokeMode::new(Color::BLACK, 10.0),
},
Transform::default(),
), …
```
=> Flatten nested MaterialMesh2dBundle

Cargo.toml, examples/rounded_polygon.rs, src/shapes.rs
Closes https://github.com/Nilirad/bevy_prototype_lyon/issues/194
- Added a `RoundedPolygon` struct in `shapes`
- Added a `rounded_polygon` example (feel free to delete)
- Introduced a dependency on `lyon_algorithms`
=> Added `RoundedPolygon`

deny.toml
- Remove ignores (no longer applicable)
- Add an ignore for `xml-rs` ([unmaintained](https://github.com/netvl/xml-rs/issues/221))
=> Update cargo deny advisories ignore

README.md
`README.md` will now link to examples in the `latest` branch, whose purpose is to host the source code for the latest release of `bevy_prototype_lyon`.
=> Link to latest release examples from README.md

README.md, examples/dynamic_shape.rs, examples/path.rs, examples/readme.rs, examples/rounded_polygon.rs, examples/svg.rs, src/plugin.rs
Breaking changes were introduced in
https://github.com/bevyengine/bevy/pull/8079
Not sure what strategy of keeping up to date with bevy this project has (master depends on bevy main branch but there are also some other branches), but this will be probably useful for anyone using bevy custom build.
=> Update code after changes of systems api in bevy

.github/workflows/ci-cron.yml, .github/workflows/dependencies.yml, Cargo.toml
Since Bevy adopted a train release schedule, it makes less sense to closely track Bevy's `main` branch. This PR will make the `master` branch depend on Bevy 0.10. I already pushed a `bevy-main` branch that tracks Bevy as we always did. I also adapted the GitHub Actions workflows to also work with `bevy-main`.
The new PR policy will be that changes should be targeted preferably on the `master` branch, while `bevy_main` is for fixing breaking changes and for using Bevy features not yet supported on release.
=> Track Bevy release on default branch

.github/workflows/ci-cron.yml, .github/workflows/ci.yml, .github/workflows/dependencies.yml
Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/Nilirad/bevy_prototype_lyon/actions/runs/4577636891:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1, actions-rs/cargo@v1, actions-rs/clippy-check@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of some of those warnings the occurrences of `actions-rs/toolchain` are replaced by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain), and the occurrences of …
=> Replace unmaintained actions-rs/* actions in CI workflows

.github/workflows/ci-cron.yml, .github/workflows/dependencies.yml, README.md, examples/dynamic_shape.rs, examples/path.rs, examples/readme.rs, examples/rounded_polygon.rs, examples/svg.rs, src/plugin.rs, src/render/mod.rs, src/shapes.rs
I noticed that the `bevy-main` branch used an older workflow configuration compared to the `master` branch. This will update `bevy-main` bringing parity between both.
=> Use GitHub Actions config from master branch

src/plugin.rs, src/render/shape_material.wgsl
bevyengine/bevy#5703 changed how WGSL shaders are imported in Bevy. This PR fixes `shape_material.wgsl` to correctly import Bevy shader structs.
=> Fix shader

CHANGELOG.md, examples/path.rs, src/entity.rs
Also fixes CI due to a breaking change in Bevy (bevyengine/bevy#9497).
=> Use `SpatialBundle`

examples/dynamic_shape.rs, examples/path.rs, examples/readme.rs, examples/rounded_polygon.rs, examples/svg.rs, src/draw.rs, src/geometry.rs, src/plugin.rs, src/vertex.rs
Needed to compile against the latest `main` branch version of `bevy`.
=> Rename `Color` to `LegacyColor`

examples/dynamic_shape.rs, examples/path.rs, examples/readme.rs, examples/rounded_polygon.rs, examples/svg.rs, src/draw.rs, src/geometry.rs, src/plugin.rs, src/vertex.rs
Reverts Nilirad/bevy_prototype_lyon#240
`LegacyColor` has been removed. Reverting to make #242 easier to merge.
=> Revert "Rename `Color` to `LegacyColor`"

Cargo.toml, examples/dynamic_shape.rs, examples/path.rs, examples/readme.rs, examples/rounded_polygon.rs, src/draw.rs, src/vertex.rs
Notable changes:
- Made methods take in `impl<Color>` instead of Color.
- Added extra bevy feature flags to dev-dependencies because of this: https://github.com/bevyengine/bevy/pull/13734
- This is only temporary, I think this is expected to get fixed in 0.14
=> Update to bevy 0.14

src/entity.rs
Little reason not to include these, as the types of all properties already implement Clone. Adding because I'd like to derive Clone in a downstream project that consumes these types.
=> Added Clone derive to ShapeBundle and Path.

src/plugin.rs
Fixes #245 
Tested with a modified example with a lot of shapes, most of which are offscreen. FPS before: 7, after: 40.
```rust
use bevy::{
color::palettes::css::*,
prelude::*,
window::{PresentMode, WindowResolution},
};
use bevy_prototype_lyon::prelude::*;
use rand::Rng;
fn main() {
App::new()
.insert_resource(Msaa::Sample4)
.add_plugins((
DefaultPlugins.set(WindowPlugin {
primary_window: Some(Window {
resolution: WindowResolution::new(1920.0, 1080.0)
.with_scale_factor_override(1.0),
present_mode: PresentMode::AutoNoVsync,
..default()
}),
..default()
}),
ShapePlugin,
))
.add_systems(Startup, setup_system)
.run();
}
fn setup_system(mut commands: Commands) {
let shape = shapes::RegularPolygon {
sides: 6,
feature: shapes::RegularPolygonFeature::Radius(20.0), …
```
=> Fix `Aabb`s and frustum culling by using default for `RenderAssetUsages`

examples/rectangle.rs, src/lib.rs, src/shapes.rs
I have added support for border radii to `Rectangle`, and I have added a new example demonstrating this.
=> Add support for border radii

CHANGELOG.md, examples/path.rs, src/entity.rs, src/geometry.rs, src/lib.rs, src/path.rs, src/shapes.rs
This change allows `ShapeBuilder` to build custom paths. `PathBuilder` has been removed. Paths can be constructed with `ShapePath`, and then be feeded to `ShapeBuilder`.
Since normal shapes uses Lyon's type `NoAttribute<BuilderImpl>` while paths use `WithSvg<BuilderImpl>`, I made `Geometry` generic over these.
=> Remove the need for `PathBuilder`

examples/dynamic_stroke_size.rs, src/entity.rs, src/plugin.rs
Making the `Shape` fields public allows for surgical modifications without requiring to rebuild the `Path` when only changes to the color or the options of some field are desired.
* Made all `Shape` attributes public.
* Added an example of changing the fill and stroke without rebuilding the path.
This works since `src/plugins.rs:mesh_shapes_system` is triggered by changes in the fields of a `Shape`.
=> Expose shape fields
